### ISSUE TITLE
WebpackOptionsValidationError: Invalid configuration object

### ISSUE THREAD

**Issue by npofopr** [nicothin/NTH-start-project#69]
Ошибка возникает на виндовой Убунте. 

```
[00:22:22] 'buildJs' errored after 2.98 s
[00:22:22] WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "/mnt/c/!Projects/new-project" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
   -> The output directory as **absolute path** (required).
    at webpack (/mnt/c/!Projects/new-project/node_modules/webpack/lib/webpack.js:31:9)
    at Stream.<anonymous> (/mnt/c/!Projects/new-project/node_modules/webpack-stream/index.js:154:38)
    at _end (/mnt/c/!Projects/new-project/node_modules/through/index.js:65:9)
    at Stream.stream.end (/mnt/c/!Projects/new-project/node_modules/through/index.js:74:5)
    at module.exports (/mnt/c/!Projects/new-project/node_modules/webpack-stream/index.js:233:12)
    at buildJs (/mnt/c/!Projects/new-project/gulpfile.js:284:11)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (/mnt/c/!Projects/new-project/node_modules/async-done/index.js:55:18)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
[00:22:22] 'default' errored after 4 s
[00:22:22] The following tasks did not complete: compileSass
[00:22:22] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! NTH-start-project@4.0.0 start: `gulp`
npm ERR! Exit status 1
```

**Comment by nicothin** [comment]
Если не меняли конфиг, то единственное что приходит в голову - воскл.знак в пути.
У меня в виндовской убунте работает нормально.

**Comment by npofopr** [comment]
Сработало. Спасибо)
